# Generated by Codex on 2026-02-12

from django.db import migrations, models


def copy_phone_to_phone_number(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.all():
        phone = getattr(profile, "phone", "")
        if phone and not getattr(profile, "phone_number", ""):
            profile.phone_number = phone
            profile.save(update_fields=["phone_number"])


def copy_phone_number_to_phone(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.all():
        phone_number = getattr(profile, "phone_number", "")
        if phone_number and not getattr(profile, "phone", ""):
            profile.phone = phone_number
            profile.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.RunPython(copy_phone_to_phone_number, copy_phone_number_to_phone),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]

